# Generated by Django 3.0.3 on 2020-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_address',
            field=models.CharField(default='Current Address', max_length=100),
        ),
    ]
