# Generated by Django 3.0.3 on 2020-02-22 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20200222_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('customer_name', models.CharField(max_length=90)),
                ('customer_email', models.CharField(max_length=111)),
                ('customer_address', models.CharField(default='', max_length=100)),
                ('customer_city', models.CharField(max_length=111)),
                ('customer_state', models.CharField(max_length=111)),
                ('customer_pin_code', models.CharField(max_length=111)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('customer_phone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_owner_phone_no',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
    ]
