# Generated by Django 3.0.3 on 2020-03-08 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20200223_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mini_order_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
