# Generated by Django 3.0.3 on 2020-03-01 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cetagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cetagory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_img', models.ImageField(null=True, upload_to='images\\restaurants-img\\')),
                ('restaurant_name', models.CharField(max_length=400)),
                ('restaurant_address', models.CharField(default='', max_length=100)),
                ('restaurant_owner_phone_no', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('mini_order_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('restaurant_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(null=True, upload_to='images\\product-img\\')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('food_preparation_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('is_veg', models.BooleanField(default=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('cetagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cetagory')),
                ('restaurant_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant')),
            ],
        ),
    ]
