# Generated by Django 3.0.3 on 2020-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200303_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
