# Generated by Django 3.0.3 on 2020-03-03 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
    ]
