# Generated by Django 3.0.3 on 2020-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200303_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='area',
            field=models.CharField(default='Geetanjali Institute of Technical Studies, Dabok', max_length=400),
        ),
        migrations.AlterField(
            model_name='addres',
            name='district',
            field=models.CharField(default='Udaipur', max_length=100),
        ),
        migrations.AlterField(
            model_name='addres',
            name='pincode',
            field=models.CharField(default='303122', max_length=6),
        ),
        migrations.AlterField(
            model_name='addres',
            name='state',
            field=models.CharField(default='Rajasthan', max_length=100),
        ),
    ]
